
package com.dds.pathfinder.itaxiinterface.wslookup;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-12/14/2009 02:16 PM(ramkris)-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CallbookerAddressLookup", targetNamespace = "http://tempuri.org/", wsdlLocation = "../standalone/data/wsdl/CallbookerAddressLookup.wsdl")
public class CallbookerAddressLookup
    extends Service
{

    private final static URL CALLBOOKERADDRESSLOOKUP_WSDL_LOCATION;
    private final static WebServiceException CALLBOOKERADDRESSLOOKUP_EXCEPTION;
    private final static QName CALLBOOKERADDRESSLOOKUP_QNAME = new QName("http://tempuri.org/", "CallbookerAddressLookup");

    public final static String ADDRESS_WSDL_FILES_PATH = "file:/" + System.getProperty("jboss.server.data.dir") + System.getProperty("file.separator")+"wsdl"+System.getProperty("file.separator")+"CallbookerAddressLookup.wsdl";

    static {
    	URL url = null;
        try {
            url = new URL(ADDRESS_WSDL_FILES_PATH);
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        CALLBOOKERADDRESSLOOKUP_WSDL_LOCATION = url;
        WebServiceException e = null;
        if (CALLBOOKERADDRESSLOOKUP_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find CallbookerAddressLookup.wsdl wsdl. Place the resource correctly in the classpath.");
        }
        CALLBOOKERADDRESSLOOKUP_EXCEPTION = e;
    }

    public CallbookerAddressLookup() {
        super(__getWsdlLocation(), CALLBOOKERADDRESSLOOKUP_QNAME);
    }

    public CallbookerAddressLookup(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALLBOOKERADDRESSLOOKUP_QNAME, features);
    }

    public CallbookerAddressLookup(URL wsdlLocation) {
        super(wsdlLocation, CALLBOOKERADDRESSLOOKUP_QNAME);
    }

    public CallbookerAddressLookup(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALLBOOKERADDRESSLOOKUP_QNAME, features);
    }

    public CallbookerAddressLookup(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CallbookerAddressLookup(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IAddressLookup
     */
    @WebEndpoint(name = "BasicHttpBinding_IAddressLookup")
    public IAddressLookup getBasicHttpBindingIAddressLookup() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IAddressLookup"), IAddressLookup.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IAddressLookup
     */
    @WebEndpoint(name = "BasicHttpBinding_IAddressLookup")
    public IAddressLookup getBasicHttpBindingIAddressLookup(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IAddressLookup"), IAddressLookup.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALLBOOKERADDRESSLOOKUP_EXCEPTION!= null) {
            throw CALLBOOKERADDRESSLOOKUP_EXCEPTION;
        }
        return CALLBOOKERADDRESSLOOKUP_WSDL_LOCATION;
    }

}
