
package com.dds.pathfinder.itaxiinterface.wslookup;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-12/14/2009 02:16 PM(ramkris)-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IAddressLookup", targetNamespace = "http://DDSAddressConnectionManagerService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IAddressLookup {


    /**
     * 
     * @param taxiCoID
     * @param orderBy
     * @param organizationName
     * @param regionAbbreviation
     * @param unitNumber
     * @param landmarkName
     * @param postCode
     * @param streetNumber
     * @param partialStreetName
     * @return
     *     returns com.dds.pathfinder.itaxiinterface.wslookup.PFAddressResponse
     */
    @WebMethod(operationName = "GetAddressData", action = "http://DDSAddressConnectionManagerService/IAddressLookup/GetAddressData")
    @WebResult(name = "GetAddressDataResult", targetNamespace = "http://DDSAddressConnectionManagerService")
    @RequestWrapper(localName = "GetAddressData", targetNamespace = "http://DDSAddressConnectionManagerService", className = "com.dds.pathfinder.itaxiinterface.wslookup.GetAddressData")
    @ResponseWrapper(localName = "GetAddressDataResponse", targetNamespace = "http://DDSAddressConnectionManagerService", className = "com.dds.pathfinder.itaxiinterface.wslookup.GetAddressDataResponse")
    public PFAddressResponse getAddressData(
        @WebParam(name = "PartialStreetName", targetNamespace = "http://DDSAddressConnectionManagerService")
        String partialStreetName,
        @WebParam(name = "StreetNumber", targetNamespace = "http://DDSAddressConnectionManagerService")
        String streetNumber,
        @WebParam(name = "UnitNumber", targetNamespace = "http://DDSAddressConnectionManagerService")
        String unitNumber,
        @WebParam(name = "RegionAbbreviation", targetNamespace = "http://DDSAddressConnectionManagerService")
        String regionAbbreviation,
        @WebParam(name = "LandmarkName", targetNamespace = "http://DDSAddressConnectionManagerService")
        String landmarkName,
        @WebParam(name = "OrganizationName", targetNamespace = "http://DDSAddressConnectionManagerService")
        String organizationName,
        @WebParam(name = "PostCode", targetNamespace = "http://DDSAddressConnectionManagerService")
        String postCode,
        @WebParam(name = "TaxiCoID", targetNamespace = "http://DDSAddressConnectionManagerService")
        Integer taxiCoID,
        @WebParam(name = "OrderBy", targetNamespace = "http://DDSAddressConnectionManagerService")
        String orderBy);

    /**
     * 
     * @param orderBy
     * @param partialRegionName
     * @param regionID
     * @return
     *     returns com.dds.pathfinder.itaxiinterface.wslookup.PFAddressResponse
     */
    @WebMethod(operationName = "GetRegionData", action = "http://DDSAddressConnectionManagerService/IAddressLookup/GetRegionData")
    @WebResult(name = "GetRegionDataResult", targetNamespace = "http://DDSAddressConnectionManagerService")
    @RequestWrapper(localName = "GetRegionData", targetNamespace = "http://DDSAddressConnectionManagerService", className = "com.dds.pathfinder.itaxiinterface.wslookup.GetRegionData")
    @ResponseWrapper(localName = "GetRegionDataResponse", targetNamespace = "http://DDSAddressConnectionManagerService", className = "com.dds.pathfinder.itaxiinterface.wslookup.GetRegionDataResponse")
    public PFAddressResponse getRegionData(
        @WebParam(name = "PartialRegionName", targetNamespace = "http://DDSAddressConnectionManagerService")
        String partialRegionName,
        @WebParam(name = "RegionID", targetNamespace = "http://DDSAddressConnectionManagerService")
        Integer regionID,
        @WebParam(name = "OrderBy", targetNamespace = "http://DDSAddressConnectionManagerService")
        String orderBy);

    /**
     * 
     * @param gpsLatitude
     * @param gpsLongitude
     * @return
     *     returns com.dds.pathfinder.itaxiinterface.wslookup.PFAddressResponse
     */
    @WebMethod(operationName = "GetClosestAddressData", action = "http://DDSAddressConnectionManagerService/IAddressLookup/GetClosestAddressData")
    @WebResult(name = "GetClosestAddressDataResult", targetNamespace = "http://DDSAddressConnectionManagerService")
    @RequestWrapper(localName = "GetClosestAddressData", targetNamespace = "http://DDSAddressConnectionManagerService", className = "com.dds.pathfinder.itaxiinterface.wslookup.GetClosestAddressData")
    @ResponseWrapper(localName = "GetClosestAddressDataResponse", targetNamespace = "http://DDSAddressConnectionManagerService", className = "com.dds.pathfinder.itaxiinterface.wslookup.GetClosestAddressDataResponse")
    public PFAddressResponse getClosestAddressData(
        @WebParam(name = "GPSLatitude", targetNamespace = "http://DDSAddressConnectionManagerService")
        Double gpsLatitude,
        @WebParam(name = "GPSLongitude", targetNamespace = "http://DDSAddressConnectionManagerService")
        Double gpsLongitude);

    /**
     * 
     * @param gpsLatitude
     * @param gpsLongitude
     * @return
     *     returns com.dds.pathfinder.itaxiinterface.wslookup.PFAddressResponse
     */
    @WebMethod(operationName = "GetClosestAddressDataRelative", action = "http://DDSAddressConnectionManagerService/IAddressLookup/GetClosestAddressDataRelative")
    @WebResult(name = "GetClosestAddressDataRelativeResult", targetNamespace = "http://DDSAddressConnectionManagerService")
    @RequestWrapper(localName = "GetClosestAddressDataRelative", targetNamespace = "http://DDSAddressConnectionManagerService", className = "com.dds.pathfinder.itaxiinterface.wslookup.GetClosestAddressDataRelative")
    @ResponseWrapper(localName = "GetClosestAddressDataRelativeResponse", targetNamespace = "http://DDSAddressConnectionManagerService", className = "com.dds.pathfinder.itaxiinterface.wslookup.GetClosestAddressDataRelativeResponse")
    public PFAddressResponse getClosestAddressDataRelative(
        @WebParam(name = "GPSLatitude", targetNamespace = "http://DDSAddressConnectionManagerService")
        Integer gpsLatitude,
        @WebParam(name = "GPSLongitude", targetNamespace = "http://DDSAddressConnectionManagerService")
        Integer gpsLongitude);

    /**
     * 
     * @param gpsLatitudeFrom
     * @param gpsLongitudeTo
     * @param gpsLongitudeFrom
     * @param locationTo
     * @param locationFrom
     * @param gpsLatitudeTo
     * @return
     *     returns com.dds.pathfinder.itaxiinterface.wslookup.PFDirectionsResponse
     */
    @WebMethod(operationName = "GetDirections", action = "http://DDSAddressConnectionManagerService/IAddressLookup/GetDirections")
    @WebResult(name = "GetDirectionsResult", targetNamespace = "http://DDSAddressConnectionManagerService")
    @RequestWrapper(localName = "GetDirections", targetNamespace = "http://DDSAddressConnectionManagerService", className = "com.dds.pathfinder.itaxiinterface.wslookup.GetDirections")
    @ResponseWrapper(localName = "GetDirectionsResponse", targetNamespace = "http://DDSAddressConnectionManagerService", className = "com.dds.pathfinder.itaxiinterface.wslookup.GetDirectionsResponse")
    public PFDirectionsResponse getDirections(
        @WebParam(name = "GPSLatitudeFrom", targetNamespace = "http://DDSAddressConnectionManagerService")
        Double gpsLatitudeFrom,
        @WebParam(name = "GPSLongitudeFrom", targetNamespace = "http://DDSAddressConnectionManagerService")
        Double gpsLongitudeFrom,
        @WebParam(name = "GPSLatitudeTo", targetNamespace = "http://DDSAddressConnectionManagerService")
        Double gpsLatitudeTo,
        @WebParam(name = "GPSLongitudeTo", targetNamespace = "http://DDSAddressConnectionManagerService")
        Double gpsLongitudeTo,
        @WebParam(name = "LocationFrom", targetNamespace = "http://DDSAddressConnectionManagerService")
        String locationFrom,
        @WebParam(name = "LocationTo", targetNamespace = "http://DDSAddressConnectionManagerService")
        String locationTo);

    /**
     * 
     * @param orderBy
     * @param organizationName
     * @param regionAbbreviation
     * @param unitNumber
     * @param landmarkName
     * @param postCode
     * @param streetNumber
     * @param partialStreetName
     * @return
     *     returns com.dds.pathfinder.itaxiinterface.wslookup.PFAddressResponse
     */
    @WebMethod(operationName = "GetLandmarkData", action = "http://DDSAddressConnectionManagerService/IAddressLookup/GetLandmarkData")
    @WebResult(name = "GetLandmarkDataResult", targetNamespace = "http://DDSAddressConnectionManagerService")
    @RequestWrapper(localName = "GetLandmarkData", targetNamespace = "http://DDSAddressConnectionManagerService", className = "com.dds.pathfinder.itaxiinterface.wslookup.GetLandmarkData")
    @ResponseWrapper(localName = "GetLandmarkDataResponse", targetNamespace = "http://DDSAddressConnectionManagerService", className = "com.dds.pathfinder.itaxiinterface.wslookup.GetLandmarkDataResponse")
    public PFAddressResponse getLandmarkData(
        @WebParam(name = "PartialStreetName", targetNamespace = "http://DDSAddressConnectionManagerService")
        String partialStreetName,
        @WebParam(name = "StreetNumber", targetNamespace = "http://DDSAddressConnectionManagerService")
        String streetNumber,
        @WebParam(name = "UnitNumber", targetNamespace = "http://DDSAddressConnectionManagerService")
        String unitNumber,
        @WebParam(name = "RegionAbbreviation", targetNamespace = "http://DDSAddressConnectionManagerService")
        String regionAbbreviation,
        @WebParam(name = "LandmarkName", targetNamespace = "http://DDSAddressConnectionManagerService")
        String landmarkName,
        @WebParam(name = "OrganizationName", targetNamespace = "http://DDSAddressConnectionManagerService")
        String organizationName,
        @WebParam(name = "PostCode", targetNamespace = "http://DDSAddressConnectionManagerService")
        String postCode,
        @WebParam(name = "OrderBy", targetNamespace = "http://DDSAddressConnectionManagerService")
        String orderBy);

    /**
     * 
     * @param taxiCoID
     * @param orderBy
     * @param partialAreaName
     * @param organizationName
     * @param regionAbbreviation
     * @param unitNumber
     * @param landmarkName
     * @param postCode
     * @param streetNumber
     * @param partialStreetName
     * @return
     *     returns com.dds.pathfinder.itaxiinterface.wslookup.PFAddressResponse
     */
    @WebMethod(operationName = "GetAreaAddress", action = "http://DDSAddressConnectionManagerService/IAddressLookup/GetAreaAddress")
    @WebResult(name = "GetAreaAddressResult", targetNamespace = "http://DDSAddressConnectionManagerService")
    @RequestWrapper(localName = "GetAreaAddress", targetNamespace = "http://DDSAddressConnectionManagerService", className = "com.dds.pathfinder.itaxiinterface.wslookup.GetAreaAddress")
    @ResponseWrapper(localName = "GetAreaAddressResponse", targetNamespace = "http://DDSAddressConnectionManagerService", className = "com.dds.pathfinder.itaxiinterface.wslookup.GetAreaAddressResponse")
    public PFAddressResponse getAreaAddress(
        @WebParam(name = "PartialStreetName", targetNamespace = "http://DDSAddressConnectionManagerService")
        String partialStreetName,
        @WebParam(name = "StreetNumber", targetNamespace = "http://DDSAddressConnectionManagerService")
        String streetNumber,
        @WebParam(name = "UnitNumber", targetNamespace = "http://DDSAddressConnectionManagerService")
        String unitNumber,
        @WebParam(name = "RegionAbbreviation", targetNamespace = "http://DDSAddressConnectionManagerService")
        String regionAbbreviation,
        @WebParam(name = "LandmarkName", targetNamespace = "http://DDSAddressConnectionManagerService")
        String landmarkName,
        @WebParam(name = "OrganizationName", targetNamespace = "http://DDSAddressConnectionManagerService")
        String organizationName,
        @WebParam(name = "PostCode", targetNamespace = "http://DDSAddressConnectionManagerService")
        String postCode,
        @WebParam(name = "PartialAreaName", targetNamespace = "http://DDSAddressConnectionManagerService")
        String partialAreaName,
        @WebParam(name = "TaxiCoID", targetNamespace = "http://DDSAddressConnectionManagerService")
        Integer taxiCoID,
        @WebParam(name = "OrderBy", targetNamespace = "http://DDSAddressConnectionManagerService")
        String orderBy);

    /**
     * 
     * @param taxiCoID
     * @param orderBy
     * @param partialAreaName
     * @param organizationName
     * @param regionAbbreviation
     * @param unitNumber
     * @param landmarkName
     * @param postCode
     * @param streetNumber
     * @param partialStreetName
     * @return
     *     returns com.dds.pathfinder.itaxiinterface.wslookup.PFAddressResponse
     */
    @WebMethod(operationName = "GetAddressDataStreets", action = "http://DDSAddressConnectionManagerService/IAddressLookup/GetAddressDataStreets")
    @WebResult(name = "GetAddressDataStreetsResult", targetNamespace = "http://DDSAddressConnectionManagerService")
    @RequestWrapper(localName = "GetAddressDataStreets", targetNamespace = "http://DDSAddressConnectionManagerService", className = "com.dds.pathfinder.itaxiinterface.wslookup.GetAddressDataStreets")
    @ResponseWrapper(localName = "GetAddressDataStreetsResponse", targetNamespace = "http://DDSAddressConnectionManagerService", className = "com.dds.pathfinder.itaxiinterface.wslookup.GetAddressDataStreetsResponse")
    public PFAddressResponse getAddressDataStreets(
        @WebParam(name = "PartialStreetName", targetNamespace = "http://DDSAddressConnectionManagerService")
        String partialStreetName,
        @WebParam(name = "StreetNumber", targetNamespace = "http://DDSAddressConnectionManagerService")
        String streetNumber,
        @WebParam(name = "UnitNumber", targetNamespace = "http://DDSAddressConnectionManagerService")
        String unitNumber,
        @WebParam(name = "RegionAbbreviation", targetNamespace = "http://DDSAddressConnectionManagerService")
        String regionAbbreviation,
        @WebParam(name = "LandmarkName", targetNamespace = "http://DDSAddressConnectionManagerService")
        String landmarkName,
        @WebParam(name = "OrganizationName", targetNamespace = "http://DDSAddressConnectionManagerService")
        String organizationName,
        @WebParam(name = "PostCode", targetNamespace = "http://DDSAddressConnectionManagerService")
        String postCode,
        @WebParam(name = "PartialAreaName", targetNamespace = "http://DDSAddressConnectionManagerService")
        String partialAreaName,
        @WebParam(name = "TaxiCoID", targetNamespace = "http://DDSAddressConnectionManagerService")
        Integer taxiCoID,
        @WebParam(name = "OrderBy", targetNamespace = "http://DDSAddressConnectionManagerService")
        String orderBy);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "TestService", action = "http://DDSAddressConnectionManagerService/IAddressLookup/TestService")
    @WebResult(name = "TestServiceResult", targetNamespace = "http://DDSAddressConnectionManagerService")
    @RequestWrapper(localName = "TestService", targetNamespace = "http://DDSAddressConnectionManagerService", className = "com.dds.pathfinder.itaxiinterface.wslookup.TestService")
    @ResponseWrapper(localName = "TestServiceResponse", targetNamespace = "http://DDSAddressConnectionManagerService", className = "com.dds.pathfinder.itaxiinterface.wslookup.TestServiceResponse")
    public String testService();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DumpData", action = "http://DDSAddressConnectionManagerService/IAddressLookup/DumpData")
    @WebResult(name = "DumpDataResult", targetNamespace = "http://DDSAddressConnectionManagerService")
    @RequestWrapper(localName = "DumpData", targetNamespace = "http://DDSAddressConnectionManagerService", className = "com.dds.pathfinder.itaxiinterface.wslookup.DumpData")
    @ResponseWrapper(localName = "DumpDataResponse", targetNamespace = "http://DDSAddressConnectionManagerService", className = "com.dds.pathfinder.itaxiinterface.wslookup.DumpDataResponse")
    public String dumpData();

    /**
     * 
     * @param taxiCoID
     * @param gpsLatitude
     * @param gpsLongitude
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "GetAreaIDForGPS", action = "http://DDSAddressConnectionManagerService/IAddressLookup/GetAreaIDForGPS")
    @WebResult(name = "GetAreaIDForGPSResult", targetNamespace = "http://DDSAddressConnectionManagerService")
    @RequestWrapper(localName = "GetAreaIDForGPS", targetNamespace = "http://DDSAddressConnectionManagerService", className = "com.dds.pathfinder.itaxiinterface.wslookup.GetAreaIDForGPS")
    @ResponseWrapper(localName = "GetAreaIDForGPSResponse", targetNamespace = "http://DDSAddressConnectionManagerService", className = "com.dds.pathfinder.itaxiinterface.wslookup.GetAreaIDForGPSResponse")
    public Integer getAreaIDForGPS(
        @WebParam(name = "GPSLatitude", targetNamespace = "http://DDSAddressConnectionManagerService")
        Double gpsLatitude,
        @WebParam(name = "GPSLongitude", targetNamespace = "http://DDSAddressConnectionManagerService")
        Double gpsLongitude,
        @WebParam(name = "TaxiCoID", targetNamespace = "http://DDSAddressConnectionManagerService")
        Integer taxiCoID);

}
